### ISSUE TITLE
Does this work with OpenBSD?

### ISSUE THREAD

**Issue by ghost** [mollusc-labs/clark#2]

**Comment by rawleyfowler** [comment]
Yes it should, as long as you find a way to pipe `syslog` output to MySQL. The deployment will be fairly different since OpenBSD doesn't have Docker. You'll need Perl >= `5.36`, Node.js & npm, and MySQL or MariaDB >= 8.0.

If you step through the `setup.pl` script you'll see how things work, though you'll need to cut the whole `rsyslog.sh` stuff (unless you find a way to get `rsyslog` on your machine) and either hack something for `syslogd`, or use CRON or some other time based callback to read logs on an interval and store them in MySQL. Rsyslog allows for direct STDERR, and SQL storage of logs, that is why it's most recommended for this.

To build, follow the steps in the `Dockerfile`, running them on the bare-metal machine.

Good luck! If you need more help leave more comments!

**Comment by ghost** [comment]
Thanks for the info, I just opened this issue to see if it worked. not because I'm planning to use it. ain't no way i'm running JS code on my OpenBSD server.

**Comment by rawleyfowler** [comment]
No worries. Well the JS would run on your clients side, the entire backend is in Perl :)

**Comment by ghost** [comment]
well ain't no way I'm serving JavaScript in my OpenBSD server.
